# Generated by Django 3.2.3 on 2022-09-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na', models.CharField(max_length=20)),
                ('sc', models.IntegerField()),
            ],
        ),
    ]
